version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nest-backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: mydatabase
    ports:
      - "3000:3000"
    networks:
      - app-network

  flask-backend:
    build:
      context: ./flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge


# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     networks:
#       - app-network
#     environment:
#       - NODE_ENV=production

#   nest-backend:
#     build:
#       context: ./nest-backend
#       dockerfile: Dockerfile
#     depends_on:
#       - db
#     environment:
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_USERNAME: myuser
#       DB_PASSWORD: mypassword
#       DB_DATABASE: mydatabase
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network
  
#   flask-backend:
#     build:
#       context: ./flask-backend
#     ports:
#       - "5000:5000"

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#     ports:
#       - "3306:3306"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
